baseURL = "https://www.aidasalova.com/"
title = "Aida Salova"
theme = "ananke"
SectionPagesMenu = "main"
preserveTaxonomyNames = true
Paginate = 6
googleAnalytics = ""
enableRobotsTXT = true
#themesDir = "../.."
resourceDir = "../resources"

[outputs]
home = ["HTML", "RSS"]

[params]
featured_image = "img/home_page.jpg"
linkedin = "https://www.linkedin.com/in/aida-salova-6128a6104/"
custom_css = ["css/custom.css"]


