baseURL = "https://www.aidasalova.com/"
title = "Let me get this right"
theme = "ananke"
SectionPagesMenu = "main"
preserveTaxonomyNames = true
Paginate = 6
googleAnalytics = "G-S1H0BCJNRZ"
enableRobotsTXT = true
#themesDir = "../.."
resourceDir = "../resources"

[outputs]
home = ["HTML", "RSS"]

[params]
featured_image = "img/puzzle.jpg"
linkedin = "https://www.linkedin.com/in/aida-salova-6128a6104/"
custom_css = ["css/custom.css"]


